# .github/workflows/checker.yml
name: PRC Board Checker

on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours at minute 0
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub beautifulsoup4

    - name: Run checker
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        GIST_ID: ${{ secrets.GIST_ID }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python prcboard-checker.py

    # Add this new step for job status notifications
    - name: Notify job status
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        SLACK_MESSAGE: "Job ${{ job.status }} for PRC Checker\n(<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Log>)"